# yamllint disable rule:line-length rule:document-start

name: parse-data
'on':
  push:
  workflow_dispatch:
    inputs:
      logMessage:
        description: 'Log message'
        required: true
        default: 'Test automation'
  schedule:
    - cron: "0 0,6,12,18 * * *"
jobs:
  parse-info:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install the requirements
        run: pip install -r requirements.txt
      - name: Download data
        env:
          BLUESKY_BOT_TOKEN: ${{ secrets.BLUESKY_BOT_TOKEN }}
        run: |
         echo "$BLUESKY_BOT_TOKEN"
         echo $BLUESKY_BOT_TOKEN
         python P0_clone_and_extract.py
         python P1_compile_results.py
         python P2_bluesky_post.py
      - name: Commit the results to the repo
        run: |
         git config user.name github-actions
         git config user.email github-actions@github.com
         git add data
         git add README.md
         git commit --allow-empty -m "GH Action: Updated from data pull dataset"
         #git push
